# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Powers <- function(X, p = 5L) {
    .Call('sarabc_Powers', PACKAGE = 'sarabc', X, p)
}

pred_sar <- function(W, X, rho, beta, p = 5L) {
    .Call('sarabc_pred_sar', PACKAGE = 'sarabc', W, X, rho, beta, p)
}

sar_abc_cpp <- function(y, X, W, rho, beta, sweights, N = 1e3L, p = 5L, no_inv = FALSE, no_moran = TRUE) {
    .Call('sarabc_sar_abc_cpp', PACKAGE = 'sarabc', y, X, W, rho, beta, sweights, N, p, no_inv, no_moran)
}

